.\" cgiSetType - Specify the result type
.\" Copyright (c) 1999 by Martin Schulze <joey@infodrom.north.de>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.TH cgiSetType 3 "15 August 1999" "CGI Library" "Programmer's Manual"
.SH NAME
cgiSetType \- Specify the result type
.SH SYNOPSYS
.nf
.B #include <cgi.h>
.sp
.BI "int cgiSetType (char *" type );
.fi
.SH DESCRIPTION
This routine sets the result type to
.IR type .
This routine may be used optional.  Default is "text/html".  It will
be used by
.BR cgiHeader (3).

.SH "RETURN VALUE"
On success 1 is returned, otherwise 0.

.SH "AUTHOR"
This CGI library is written by Martin Schulze
<joey@infodrom.north.de>.  If you have additions or improvements
please get in touch with him.

.SH "SEE ALSO"
.BR cgiHeader (3),
.BR cgiSetHeader (3),
.BR cgiInit (3).
